version: "3"

services:

    zk1:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk1
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 12181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 12181:12181
            - 12888:12888
            - 13888:13888
        volumes:
            - /zk-kafka/zookeeper/data:/var/lib/zookeeper/data
            - /zk-kafka/zookeeper/log:/var/lib/zookeeper/log
            - /zk-kafka/zookeeper/secrets:/etc/zookeeper/secrets
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 1

    zk2:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk2
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: 22181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 22181:22181
            - 22888:22888
            - 23888:23888
        volumes:
            - /zk-kafka/zookeeper/data:/var/lib/zookeeper/data
            - /zk-kafka/zookeeper/log:/var/lib/zookeeper/log
            - /zk-kafka/zookeeper/secrets:/etc/zookeeper/secrets
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 2

    zk3:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk3
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 32181:32181
            - 32888:32888
            - 33888:33888
        volumes:
            - /zk-kafka/zookeeper/data:/var/lib/zookeeper/data
            - /zk-kafka/zookeeper/log:/var/lib/zookeeper/log
            - /zk-kafka/zookeeper/secrets:/etc/zookeeper/secrets
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 3

    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
            KAFKA_DELETE_TOPIC_ENABLE: true
        ports:
            - 19092:19092
        volumes:
            - /zk-kafka/kafka/data:/var/lib/kafka/data
            - /zk-kafka/kafka/secrets:/etc/kafka/secrets
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 1
    
    kafka2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
            KAFKA_DELETE_TOPIC_ENABLE: true
        ports:
            - 29092:29092
        volumes:
            - /zk-kafka/kafka/data:/var/lib/kafka/data
            - /zk-kafka/kafka/secrets:/etc/kafka/secrets
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 2

    kafka3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
            KAFKA_DELETE_TOPIC_ENABLE: true
        ports:
            - 39092:39092
        volumes:
            - /zk-kafka/kafka/data:/var/lib/kafka/data
            - /zk-kafka/kafka/secrets:/etc/kafka/secrets
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 3
