version: "3"

services:

    zk:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: $ZK_SERVER_ID
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: $ZK_CLUSTER_URL
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        deploy:
            mode: global
            placement:
                constraints: [node.labels.zookeeper == true]

    kafka:
        image: confluentinc/cp-kafka:latest
        environment:
            KAFKA_BROKER_ID: $KAFKA_BROKER_ID
            KAFKA_ZOOKEEPER_CONNECT: $ZK_KAFKA_CLUSTER_CONN_URL
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$EXTERNAL_IP:9092
        depends_on:
            - zk
        deploy:
            mode: global
            placement:
                constraints: [node.labels.kafka == true]
