version: "3"

services:

    zk1:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk1
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 12181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 2181:12181
            - 2888:12888
            - 3888:13888
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 1

    zk2:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk2
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: 22181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 2181:22181
            - 2888:22888
            - 3888:23888
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 2

    zk3:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk3
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
        ports:
            - 2181:32181
            - 2888:32888
            - 3888:33888
        deploy:
            placement:
                constraints: 
                    - node.labels.zookeeper == true
                    - node.labels.zookeeper.id == 3

    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: kafka1:2181,kafka2:2181,kafka3:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
        ports:
            - 9092:19092
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 1
    
    kafka2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: kafka1:2181,kafka2:2181,kafka3:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
        ports:
            - 9092:29092
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 2

    kafka3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: kafka1:2181,kafka2:2181,kafka3:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
        ports:
            - 9092:39092
        depends_on:
            - zk1
            - zk2
            - zk3
        deploy:
            placement:
                constraints:
                    - node.labels.kafka == true
                    - node.labels.kafka.id == 3
