version: "3"

services:

    zk:
        image: confluentinc/cp-zookeeper:latest
        hostname: zk-$HOSTNAME
        environment:
            ZOOKEEPER_SERVER_ID: $ZK_SERVER_ID
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: $ZK_CLUSTER_URL
        deploy:
            placement:
                constraints: [node.labels.zookeeper == true]
        network_mode: host

    kafka:
        image: confluentinc/cp-kafka:latest
        hostname: kafka-$HOSTNAME
        environment:
            KAFKA_BROKER_ID: $KAFKA_BROKER_ID
            KAFKA_ZOOKEEPER_CONNECT: $ZK_KAFKA_CLUSTER_CONN_URL
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-$HOSTNAME:9092
        depends_on:
            - zk
        deploy:
            placement:
                constraints: [node.labels.kafka == true]
       network_mode: host
